
format = """
[](#c6a0f6)\
$username\
[](bg:#ed8797 fg:#c6a0f6)\
$directory\
[](fg:#ed8797 bg:#f5a97f)\
$git_branch\
$git_status\
[](fg:#f5a97f bg:#eed49f)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#eed49f bg:#a7da96)\
$docker_context\
[](fg:#a7da96 bg:#8badf4)\
$time\
[ ](fg:#8badf4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#c6a0f6 fg:#000000"
style_root = "bg:#c6a0f6 fg:#000000"
format = '[$user ]($style)'

[directory]
style = "bg:#ed8797 fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#a7da96 fg:#000000"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#eed49f fg:#000000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8badf4 fg:#000000"
format = '[ ♥ $time ]($style)'

