theme = "custom_kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
select = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
space = { x = ":buffer-close" }
V = ["select_mode", "extend_to_line_bounds"]
Y = ":clipboard-yank"

[keys.select]
Y = ":clipboard-yank"

[keys.insert]
C-space = "completion"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["version-control"]
mode.insert = "DEEZ"
mode.normal = "NUTZ"
mode.select = "(⌐▨_▨)"

[editor.file-picker]
hidden = false
