theme = "catppuccin_frape"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
select = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
space = { x = ":buffer-close" }
V = ["select_mode", "extend_to_line_bounds"]
# X = "extend_line_above"

[keys.select]
Y = ":clipboard-yank"

[editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
# separator = "x"
mode.normal = "BALLS"
mode.insert = "LIGMA"
mode.select = "(⌐▨_▨)"

# ░▒▓
# ┬──┬◡ﾉ(° -°ﾉ)
# (╯’□’)╯︵ ┻━┻
# (⌐▨_▨) (⌐■_■)

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[editor.file-picker]
hidden = false
