theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
select = "block"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
space = { x = ":buffer-close" }
# X = "extend_line_above"

[editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "( •_•)"
mode.insert = "(〜^∇^)〜"
mode.select = "(⌐▨_▨)"

# ┬──┬◡ﾉ(° -°ﾉ)
# (╯’□’)╯︵ ┻━┻
# (⌐▨_▨) (⌐■_■)

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
