theme = "base16_transparent"

[editor]
line-number = "relative"
color-modes = false
auto-pairs = false
scrolloff = 7
mouse = false
cursorline = false
popup-border = "all"
end-of-line-diagnostics = "hint"
# bufferline = "multiple"
# rulers = [80]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
V = ["select_mode", "extend_to_line_bounds"]
Y = ":clipboard-yank"
X = ["extend_line_up", "extend_to_line_bounds"]
G = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
ret = "goto_word"
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
P = ":clipboard-paste-before"
# yazi config
Cmd-f = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
# yazi config end

# C-f = [
# ":new",
# ":insert-output lf-pick",
# ":theme default",
# "select_all",
# "split_selection_on_newline",
# "goto_file",
# "goto_last_modified_file",
# ":buffer-close!",
# ":theme heisenberg",
# ]

[keys.normal.space]
x = ":buffer-close"
X = ":buffer-close!"
l = "last_picker"
"=" = ":format"
"+" = ":reload"
i = ":toggle lsp.display-inlay-hints"
space = "buffer_picker"
f = "file_picker_in_current_directory"
F = "file_picker"
b = "file_picker_in_current_buffer_directory"

[keys.select]
S-tab = ":buffer-previous"
tab = ":buffer-next"
Y = ":clipboard-yank"
G = "goto_file_end"
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.select.space]
x = ":buffer-close"

# [keys.insert]
# C-space = "completion"

[editor.statusline]
left = [
  "spacer",
  "mode",
  "file-name",
  "spacer",
  "position-percentage",
  "spacer",
  "spinner",
]
separator = "│"
right = ["version-control", "spacer", "file-modification-indicator", "spacer"]
mode.insert = "インサート"
mode.normal = "ノーマル"
mode.select = "(⌐▨_▨)"
