theme = "tokyonight"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
