inherits = "kanagawa"

"ui.background" = { bg = "#000000" }

"ui.selection" = { bg = "base" }

"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "base", bg = "rosewater" }
"ui.cursor.match" = { fg = "#FF5D62", modifiers = ["bold"] }

"ui.menu.selected" = { fg = "#FF5D62" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.statusline.normal" = { bg = "#7FB4CA", modifiers = ["bold"], fg = "#000000" }
"ui.statusline.insert" = { bg = "#98BB6C", modifiers = ["bold"], fg = "#000000" }
"ui.statusline.select" = { bg = "#FF9E3B", modifiers = ["bold"], fg = "#000000" }
"ui.statusline.separator" = { bg = "#FF9E3B", fg = "#FF9E3B" }

"ui.bufferline.background" = { bg = "#16161D" }
"ui.bufferline.active" = { fg = "#FF5D62", modifiers = ["bold"] }

"ui.statusline" = { modifiers = ["bold"], bg = "#16161D" }

"ui.linenr.selected" = { fg = "#FF5D62" }

"ui.menu.scroll" = { fg = "#FF5D62" }

[palette]
# catppuccin palette colors
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"

text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"

base = "#303446"
mantle = "#292c3c"
crust = "#232634"

# derived colors by blending existing palette colors
cursorline = "#3b3f52"
secondary_cursor = "#b8a5a6"
